### ISSUE TITLE
Text about armies defeating mage available before creating arrows

### ISSUE THREAD

**Issue by brirush84** [andrewschultz/there-those-dare-doze#2]
I made some fair foes and bare bows, but didn't have to make arrows before going south, as it assumed I had them.

**Comment by andrewschultz** [comment]
Thanks for this report!

There was so much to unpack here to fix all the bugs, which is why I took a while to respond.

A two-part fix. If you're curious about the commits:
https://github.com/andrewschultz/there-those-dare-doze/commit/af590e1fec04d3a4fb06a65ca10be78dec9543cc got things started.

The next one is auto-linked above by github. It contains one of Zarf's test scripts.
