### ISSUE TITLE
Some possible rhymes

### ISSUE THREAD

**Issue by brirush84** [andrewschultz/there-those-dare-doze#3]
Some of these I later realized are used in-text, either at the beginning and end of the game. Others aren't, though.

tear toes
wear woes
ware woes
hair hoes
hare hoes
layer lows
lair lows
share shows
ne'er nose
nair nose
pair pose
pear pose
claire close
air ohs
ere ohs
there those
flare flows
flair flows

bower boom

declare declose
impair impose
mayor mose/moes/mows

fave found

bam beak
slam sleek
lamb leek
lamb leak

mope muts

**Comment by andrewschultz** [comment]
Thanks very much! It turned out all 3 of your issues helped/made me drill deeply and I found some interesting stuff to tweak.

There were lots of good rhymes here, and they'll obviously help the player get the hint item quicker, among other thngs. I'd been delaying this because I had a piece of paper where I misplaced my notes. Also, one of these guesses is so good, I transitioned it to a point-scoring rhyme in the post-comp version, replacing another guess.

And definitely, don't worry about any duplicates -- I'd rather have things get double covered than not at all!

You mentioned some guesses were referred to obliquely in the text, but some I wanted to make clearer. For instance, I still want to flag "share shows" which is mentioned in the intro, but I don't have a suitable intuitive way to do that, yet.

I have a feeling I an obvious trick, so maybe there will be another commit later! If so, maybe I can use it in other post-comp release.

Oh, you're also in the credits as someone who helped in-comp.
